import xlwt
# criar um arquivo em branco
w = xlwt.Workbook()
# criar uma planilha no arquivo
ws = w.add_sheet('Prova')

# adicionar uma nova cor com os parâmetros RGB
xlwt.add_palette_colour("custom_colour", 0x21)
w.set_colour_RGB(0x21, 251, 228, 228)

headline = xlwt.easyxf('pattern: pattern solid, fore_colour gray25; border: bottom thick, top thick, right thick; font: bold on; align: wrap on, vert centre, horiz left')
style1 = xlwt.easyxf('pattern: pattern solid, fore_colour pale_blue')
# escrever em uma célula
ws.write(0,0,'prova_ano',style=headline)
ws.write(0,1,'prova_esfera',style=headline)
ws.write(0,2,'prova_banca',style=headline)
ws.write(0,3,'prova_tipo',style=headline)
ws.write(0,4,'prova_escolaridade',style=headline)
ws.write(0,5,'prova_area',style=headline)
ws.write(0,6,'prova_instituto',style=headline)
ws.write(0,7,'prova_instituto_uf',style=headline)
ws.write(0,8,'prova_instituto_municipio',style=headline)
ws.write(0,9,'prova_supercargo',style=headline)
ws.write(0,10,'prova_cargo',style=headline)
ws.write(0,11,'prova_ninscritos_tot',style=headline)
ws.write(0,12,'prova_ninscritos_amplo',style=headline)
ws.write(0,13,'prova_ninscritos_negro',style=headline)
ws.write(0,14,'prova_ninscritos_def',style=headline)
ws.write(0,15,'prova_nota_max_amplo',style=headline)
ws.write(0,16,'prova_nota_max_negro',style=headline)
ws.write(0,17,'prova_prova_nota_max_def',style=headline)
ws.write(0,18,'prova_corte_amplo',style=headline)
ws.write(0,19,'prova_corte_negro',style=headline)
ws.write(0,20,'prova_corte_def',style=headline)
ws.write(0,21,'quest_materia',style=headline)
ws.write(0,22,'quest_anulada',style=headline)
ws.write(0,23,'quest_obs',style=headline)
ws.write(0,24,'quest_txt_ass',style=headline)
ws.write(0,25,'quest_no',style=headline)
ws.write(0,26,'quest_corpo',style=headline)
ws.write(0,27,'assert_letra',style=headline)
ws.write(0,28,'assert_corpo',style=headline)
ws.write(0,29,'assert_correta',style=headline)
ws.write(0,30,'assert_jurisprudencia',style=headline)
ws.write(0,31,'assert_doutrina',style=headline)
ws.write(0,32,'assert_obs',style=headline)
ws.write(0,33,'lei_municipio',style=headline)
ws.write(0,34,'lei_uf',style=headline)
ws.write(0,35,'lei_esfera',style=headline)
ws.write(0,36,'lei_tipo',style=headline)
ws.write(0,37,'lei_diploma',style=headline)
ws.write(0,38,'lei_ano',style=headline)
ws.write(0,39,'lei_artigo',style=headline)
ws.write(0,40,'lei_paragrafo',style=headline)
ws.write(0,41,'lei_inciso',style=headline)
ws.write(0,42,'lei_alinea',style=headline)
ws.write(0,43,'prova_alt_art_tipo',style=headline)
ws.write(0,44,'lei_alt_art_diploma',style=headline)
ws.write(0,45,'lei_alt_art_ano',style=headline)
ws.write(0,46,'lei_alt_paragrafo_tipo',style=headline)
ws.write(0,47,'lei_alt_paragrafo_diploma',style=headline)
ws.write(0,48,'lei_alt_paragrafo_ano',style=headline)
ws.write(0,49,'lei_alt_inciso_tipo',style=headline)
ws.write(0,50,'lei_alt_inciso_diploma',style=headline)
ws.write(0,51,'lei_alt_inciso_ano',style=headline)
ws.write(0,52,'lei_alt_alinea_tipo',style=headline)
ws.write(0,53,'lei_alt_alinea_diploma',style=headline)
ws.write(0,54,'lei_alt_alinea_ano',style=headline)
ws.write(0,55,'sumula_entidade',style=headline)
ws.write(0,56,'sumula_numero',style=headline)
ws.write(0,57,'sumula_vinculante',style=headline)
ws.write(0,58,'oj_entidade',style=headline)
ws.write(0,59,'oj_numero',style=headline)
ws.write(0,60,'enun_entidade',style=headline)
ws.write(0,61,'enun_numero',style=headline)

ws.write_merge(1,1,0,20,style=style1)
# salvar o arquivo
w.save('exemplo_planilha.xls')

